import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "../globals.css";
import { Logo } from "@/shared/components";

const notoSans = Noto_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.className} antialiased`}>
        <div className="min-h-screen flex justify-center items-center">
          <div className="w-[360px]">
            <div className="mb-14 text-center">
              <Logo />
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
